<a href="https://colab.research.google.com/github/gwalshe73/TFDC2021ZtoM/blob/main/00_TensorFlow_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# In this notebook we're going to cover some of the most fundamental concepts of tensors using TensorFlow

More specifically, we're going to cover:
* Introduction to tensors
* Getting information from tensors
* Manipulating tensors
* Tensors & NumPy
* Using @tf.function (a way to speed up your regular Python functions)
* Using GPUs with TensorFlow (or TPUs)
* Exercises to try for yourself!


### Introduction to Tensors

In [1]:
# Import TensorFlow
import tensorflow as tf
print(tf.__version__)

2.5.0


In [2]:
# Create tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
# Check the number of dimensions of a tensor (ndim stands for number of dimensions)
scalar.ndim

0

In [4]:
# Create a vector
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [5]:
vector.ndim

1

In [6]:
# Create a matrix
matrix = tf.constant([[10, 7],
                      [7, 10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [7]:
matrix.ndim

2

In [8]:
# Create another matrix
another_matrix = tf.constant([[10., 7.],
                              [3., 2.],
                              [8., 9.]], dtype=tf.float16) # specify the data type with dtype parameter
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [9]:
another_matrix.ndim

2

In [10]:
# Let's create a tensor
tensor = tf.constant([[[1, 2, 3],
                       [4, 5, 6]],
                      [[7, 8, 9],
                       [10, 11, 12]],
                      [[13, 14, 15],
                       [16, 17, 18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [11]:
tensor.ndim

3

What we've created so far:

* Scalar: a single number
* Vector: a number with direction (e.g. wind speed and direction)
* Matrix: a 2-dimensional array of numbers
* Tensor: an n-dimensional array of numbers (when n can be any number, a 0-dimensional tensor is a scalar, a 1-dimensional tensor is a vector)

### Creating tensors with tf.variable

In [12]:
# Create the same tensor with tf.variable() as above
changeable_tensor = tf.Variable([10, 7])
unchangeable_tensor = tf.constant([10, 7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [13]:
# Let's change our changeable tensor
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [15]:
# Let's change our unchangeable tensor
unchangeable_tensor[0].assign(7)
unchangeable_tensor

AttributeError: ignored

**Note:** Rarely in practice will you need to decide whether to use `tf.constant` or `tf.variable` to create tensors, as TensorFlow does this for you. However, if in doubt, use `tf.constant` and change it later if needed.

### Creating random tensors

Random tensors are tensors of some arbitrary size which contain random numbers.

In [16]:
# Create two random (but the same) tensors
random_1 = tf.random.Generator.from_seed(42) # set seed for reproduceability
random_1 = random_1.normal(shape=(3, 2))
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3, 2))

# Are they equal?
random_1, random_2, random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

### Shuffle the order of elements in a tensor

In [17]:
# Shuffle a tensor (valuable for when you want to shuffle your data so the inherent order doesn't affect learning)
not_shuffled = tf.constant([[10, 7],
                            [3, 4],
                            [2, 5]])
# Shuffle our non-shuffled tensor
tf.random.shuffle(not_shuffled, seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [ 3,  4],
       [10,  7]], dtype=int32)>

In [18]:
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [19]:
tf.random.set_seed(42) # Global randon seed
tf.random.shuffle(not_shuffled, seed=42) # Operation level seed

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

### Other ways to make tensors

In [20]:
# Create a tensor of all ones
tf.ones([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [21]:
# Create a tensor of all zeroes
tf.zeros([3, 4])

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

### Turn NumPy arrays into tensors

The main difference between NumPy arrays and TensorFlow tensors is thay tensors can be run on a GPU (much faster for numerical computing).

In [22]:
# You can also turn NumPy arrays into tensors
import numpy as np
numpy_A = np.arange(1, 25, dtype=np.int32) # Create a NumPy array between 1 and 25
numpy_A

# X = tf.constant(some_matrix) # capital for matrix or tensor
# y = tf.constant(vector) # non-capital for vector

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [23]:
A = tf.constant(numpy_A, shape=(2, 3, 4))
B = tf.constant(numpy_A)
A, B

(<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]], dtype=int32)>,
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>)

In [24]:
A.ndim

3

In [25]:
B.ndim

1

### Getting information from tensors

When dealing with tensors you will probably want to be aware of the following attributes:
* shape
* Rank
* Axis or dimension
* Size

In [26]:
# Create a rank 4 tensor (4 dimensions)
rank_4_tensor = tf.zeros(shape=[2,3,4,5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [27]:
rank_4_tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [28]:
rank_4_tensor.shape

TensorShape([2, 3, 4, 5])

In [29]:
rank_4_tensor.ndim

4

In [30]:
tf.size(rank_4_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=120>

In [31]:
# Get various attributes of our tensor
print("Datatype of every element:", rank_4_tensor.dtype)
print("Number of dimensions (rank):", rank_4_tensor.ndim)
print("Shape of tensor:", rank_4_tensor.shape)
print("Elements along the 0 axis:", rank_4_tensor.shape[0])
print("Elements along the last axis:", rank_4_tensor.shape[-1])
print("Total number of elements in our tensor:", tf.size(rank_4_tensor))
print("Total number of elements in our tensor:", tf.size(rank_4_tensor).numpy())

Datatype of every element: <dtype: 'float32'>
Number of dimensions (rank): 4
Shape of tensor: (2, 3, 4, 5)
Elements along the 0 axis: 2
Elements along the last axis: 5
Total number of elements in our tensor: tf.Tensor(120, shape=(), dtype=int32)
Total number of elements in our tensor: 120


### Indexing tensors

Tensors can be indexed just like Python lists.

In [32]:
some_list = [1, 2, 3, 4]
some_list[:2]

[1, 2]

In [33]:
# Get the first 2 elements of each dimension
rank_4_tensor[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [34]:
# Get the first element from each dimension from each index except for the last one
rank_4_tensor[:1, :1, :1, :]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [35]:
rank_4_tensor.shape

TensorShape([2, 3, 4, 5])

In [36]:
rank_4_tensor[:1, :1, :, :1]

<tf.Tensor: shape=(1, 1, 4, 1), dtype=float32, numpy=
array([[[[0.],
         [0.],
         [0.],
         [0.]]]], dtype=float32)>

In [37]:
# Create a rank 2 tensor (2 dimensions)
rank_2_tensor = tf.constant([[10, 7],
                             [3, 4]])
rank_2_tensor.shape, rank_2_tensor.ndim

(TensorShape([2, 2]), 2)

In [38]:
# Get the last item of each row of our rank 2 tensor
rank_2_tensor[:, -1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4], dtype=int32)>

In [39]:
# Add in extra dimension to our rank 2 tensor
rank_3_tensor = rank_2_tensor[..., tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [40]:
# Alternative to tf.newaxis
tf.expand_dims(rank_2_tensor, axis=-1) # "-1" means expand the final axis

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [41]:
# Expand the 0 axis
tf.expand_dims(rank_2_tensor, axis=0) # Expamd the 0 axis

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[10,  7],
        [ 3,  4]]], dtype=int32)>

### Manipulating tensors (tensor operations)

**Basic operations**

In [42]:
# You can add values to a tensor using the addition operator
tensor = tf.constant([[10, 7],
                      [3, 4]])
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [43]:
# Original tensor is unchanged
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [44]:
# Multiplication also works
tensor * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [45]:
# Subtraction also
tensor - 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -6]], dtype=int32)>

In [46]:
# Division also
tensor / 10

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[1. , 0.7],
       [0.3, 0.4]])>

In [47]:
# We can use the tensorflow built in functions also
tf.multiply(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [48]:
tf.divide(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[1. , 0.7],
       [0.3, 0.4]])>

In [49]:
tf.add(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [50]:
tf.subtract(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -6]], dtype=int32)>

In [51]:
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

### Matrix multiplication

In machine learning, matrix multiplication is one of the most common tensor operations.

In [52]:
# Matrix multiplication in tensor
print(tensor)

tf.Tensor(
[[10  7]
 [ 3  4]], shape=(2, 2), dtype=int32)


In [53]:
tf.matmul(tensor, tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [54]:
tensor * tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  49],
       [  9,  16]], dtype=int32)>

In [55]:
# Matrix multiplication with Python operator '@'
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [56]:
tensor.shape

TensorShape([2, 2])

In [57]:
# Create a tensor (3, 2)
X = tf.constant([[1, 2],
                 [3, 4],
                 [5, 6]])
# Create another (3, 2) tensor
Y = tf.constant([[7, 8],
                 [9, 10],
                 [11, 12]])
X, Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>, <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [59]:
# Try to matrix multiply tensors of the same shape
X @ Y

InvalidArgumentError: ignored

In [61]:
tf.matmul(X, Y)

InvalidArgumentError: ignored

In [62]:
X.shape, Y.shape

(TensorShape([3, 2]), TensorShape([3, 2]))

In [63]:
tf.transpose(Y)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 7,  9, 11],
       [ 8, 10, 12]], dtype=int32)>

In [64]:
X @ tf.transpose(Y)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

In [65]:
tf.matmul(X, tf.transpose(Y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

In [66]:
tf.matmul(X, tf.reshape(Y, shape=(2, 3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

### **`tf.transpose` gives an proper matrix flip, do not use ``tf.reshape()``!**

### **The dot product**
Matrix multiplication is also referred to as the dot product.

You can perform matrix multiplication using:
* ``tf.matmul()``
* ``tf.tensordot()``


In [67]:
# Perform the dot product on X and Y (requires X or Y to be transposed)
tf.tensordot(tf.transpose(X), Y, axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [68]:
X, tf.transpose(X)

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>, <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 3, 5],
        [2, 4, 6]], dtype=int32)>)

# Exercises

### 1. Create a scalar, vector, matrix and tensor using ``tf.constant()``

In [70]:
# Scalar
scalar = tf.constant(10)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [72]:
# Vector
vector = tf.constant([10, 5])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  5], dtype=int32)>

In [73]:
# Matrix
matrix = tf.constant([[11, 4],
                      [3,15]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[11,  4],
       [ 3, 15]], dtype=int32)>

In [78]:
# Tensor
tensor = tf.constant([[[2, 5],
                      [5, 1],
                      [6, 78]],
                      [[4, 7],
                       [3, 9],
                       [45,54]]])
tensor

<tf.Tensor: shape=(2, 3, 2), dtype=int32, numpy=
array([[[ 2,  5],
        [ 5,  1],
        [ 6, 78]],

       [[ 4,  7],
        [ 3,  9],
        [45, 54]]], dtype=int32)>

### 2. Find the shape, rank and size of the tensors

In [83]:
# Scalar
scalar.shape, scalar.ndim, tf.size(scalar)

(TensorShape([]), 0, <tf.Tensor: shape=(), dtype=int32, numpy=1>)

In [84]:
# Vector
vector.shape, vector.ndim, tf.size(vector)

(TensorShape([2]), 1, <tf.Tensor: shape=(), dtype=int32, numpy=2>)

In [85]:
# Matrix
matrix.shape, matrix.ndim, tf.size(matrix) 

(TensorShape([2, 2]), 2, <tf.Tensor: shape=(), dtype=int32, numpy=4>)

In [86]:
# Tensor
tensor.shape, tensor.ndim, tf.size(tensor)

(TensorShape([2, 3, 2]), 3, <tf.Tensor: shape=(), dtype=int32, numpy=12>)

### 3. Create 2 tensors containing random values between 0 and 1 with shape [5, 300]

In [92]:
t1 = tf.random.normal([5, 300])
t2 = tf.random.normal([5, 300])
t1, t2

(<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
 array([[ 0.0307604 ,  0.29017973,  1.2829775 , ..., -0.31561375,
          0.6939584 ,  0.21943499],
        [ 0.33295122,  2.1236846 , -1.2140282 , ...,  0.89139235,
         -1.3493335 ,  0.5633818 ],
        [-0.9233208 ,  2.001058  ,  0.72869575, ..., -1.2967669 ,
          0.4724821 ,  3.059215  ],
        [ 0.7984267 , -0.7516271 ,  0.57440645, ...,  0.37882376,
         -1.0226766 , -1.4862266 ],
        [ 0.38326833,  0.26799828, -1.4706461 , ..., -0.79758877,
          0.7815208 , -1.0841022 ]], dtype=float32)>,
 <tf.Tensor: shape=(5, 300), dtype=float32, numpy=
 array([[-0.20061125, -1.2735859 ,  0.48410097, ...,  1.8554242 ,
          1.4968362 ,  0.25604418],
        [ 0.04510723,  0.35246333, -0.4582101 , ..., -1.0423009 ,
          0.3514297 , -0.05300916],
        [ 0.5467766 , -0.13111319,  0.45419455, ...,  0.0728109 ,
          0.93484294, -0.23334979],
        [ 0.45130223,  0.40723053,  0.6458354 , ...,  1.306083  

### 4. Multiply the 2 tensors created in 3 using matrix multiplication

In [94]:
tf.matmul(t1, tf.transpose(t2))

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[ 24.178051  ,  17.66863   ,  -0.80400276, -23.825283  ,
         38.139626  ],
       [ -1.9231691 ,  18.065163  , -20.516472  , -46.27577   ,
         -1.5878363 ],
       [  3.0509634 ,  23.437424  ,  15.738693  , -17.186628  ,
         13.11319   ],
       [-10.397989  , -10.5653515 ,  25.733967  ,  18.766771  ,
          3.2997217 ],
       [ -9.753842  ,  -0.7893524 ,   8.554968  ,  -2.3906887 ,
         -4.084072  ]], dtype=float32)>

### 5. Multiply the 2 tensors created in 3 using dotproduct

In [101]:
tf.tensordot(t1, tf.transpose(t2), axes=1)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[ 24.178051  ,  17.66863   ,  -0.80400276, -23.825283  ,
         38.139626  ],
       [ -1.9231691 ,  18.065163  , -20.516472  , -46.27577   ,
         -1.5878363 ],
       [  3.0509634 ,  23.437424  ,  15.738693  , -17.186628  ,
         13.11319   ],
       [-10.397989  , -10.5653515 ,  25.733967  ,  18.766771  ,
          3.2997217 ],
       [ -9.753842  ,  -0.7893524 ,   8.554968  ,  -2.3906887 ,
         -4.084072  ]], dtype=float32)>

### 6. Create a tensor with randowm values between 0 an 1 with shape [224, 224, 3]

In [102]:
tensor = tf.random.normal([224, 224, 3])
tensor

<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
array([[[ 1.1442094 , -1.6089787 , -1.347222  ],
        [-0.6169336 ,  0.8454657 ,  0.15746248],
        [-0.25251707,  0.95594734,  1.4579884 ],
        ...,
        [ 0.16952473, -0.27997565,  0.43211383],
        [ 0.3734655 , -0.2055831 ,  1.6724342 ],
        [-0.48485023,  0.60599244, -0.98848474]],

       [[ 0.5445747 ,  1.5859115 ,  0.40635926],
        [-0.52796876, -0.3661996 , -0.22763297],
        [ 0.7203257 ,  0.6607731 , -1.1420876 ],
        ...,
        [-0.52681863, -1.3980784 ,  0.37619415],
        [ 0.59879106,  0.5491657 , -0.44797382],
        [ 0.7599017 , -0.36187738, -0.7250368 ]],

       [[ 0.17918585,  1.4783044 ,  0.5025955 ],
        [-0.52634865,  1.0325756 ,  1.9047203 ],
        [-0.331364  ,  0.758236  , -0.36835626],
        ...,
        [ 0.45533064, -0.2826367 ,  1.0735812 ],
        [-0.32927358, -0.63785857,  0.02804685],
        [ 1.1212776 , -1.5463754 , -1.1714389 ]],

       ...,

     

### 7. Find the min and max values of the tensor created in 6

In [110]:
tf.reduce_min(tensor)

<tf.Tensor: shape=(), dtype=float32, numpy=-4.622507>

In [111]:
tf.reduce_max(tensor)

<tf.Tensor: shape=(), dtype=float32, numpy=4.957513>

### 8. Create a tensor with random values of shape [1, 224, 224, 3] then squeeze it to change the shape to [224, 224, 3]

In [117]:
tensor = tf.random.normal([1, 224, 224, 3])
tensor

<tf.Tensor: shape=(1, 224, 224, 3), dtype=float32, numpy=
array([[[[ 0.6221494 ,  0.39071774,  0.5728211 ],
         [ 0.92682797,  0.8460992 ,  0.08634651],
         [-0.39511812, -0.02012417,  1.0490924 ],
         ...,
         [ 0.16337813, -0.29364723,  1.6534562 ],
         [ 0.40436256, -0.08578903,  0.91270536],
         [ 1.2697189 , -1.2756239 ,  0.03109276]],

        [[ 1.4886796 , -0.33158135, -0.31238177],
         [-0.5563497 , -0.24287094,  0.7662552 ],
         [ 0.6512325 ,  0.47333828,  0.78456104],
         ...,
         [ 1.108035  , -0.31234267,  0.16275364],
         [-2.8403242 ,  0.609528  , -0.4213753 ],
         [-0.5680991 ,  0.03625574, -0.9237544 ]],

        [[ 0.9157403 , -1.6512513 , -1.007297  ],
         [-1.653329  ,  0.5590685 ,  0.876366  ],
         [-1.0728643 , -1.7195888 ,  0.3131277 ],
         ...,
         [-2.069528  ,  0.40379855,  0.20493232],
         [ 0.8386405 , -0.84751904,  0.46400514],
         [-0.2258632 ,  0.3818766 ,  1.41984  

In [118]:
tf.squeeze(tensor)

<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
array([[[ 0.6221494 ,  0.39071774,  0.5728211 ],
        [ 0.92682797,  0.8460992 ,  0.08634651],
        [-0.39511812, -0.02012417,  1.0490924 ],
        ...,
        [ 0.16337813, -0.29364723,  1.6534562 ],
        [ 0.40436256, -0.08578903,  0.91270536],
        [ 1.2697189 , -1.2756239 ,  0.03109276]],

       [[ 1.4886796 , -0.33158135, -0.31238177],
        [-0.5563497 , -0.24287094,  0.7662552 ],
        [ 0.6512325 ,  0.47333828,  0.78456104],
        ...,
        [ 1.108035  , -0.31234267,  0.16275364],
        [-2.8403242 ,  0.609528  , -0.4213753 ],
        [-0.5680991 ,  0.03625574, -0.9237544 ]],

       [[ 0.9157403 , -1.6512513 , -1.007297  ],
        [-1.653329  ,  0.5590685 ,  0.876366  ],
        [-1.0728643 , -1.7195888 ,  0.3131277 ],
        ...,
        [-2.069528  ,  0.40379855,  0.20493232],
        [ 0.8386405 , -0.84751904,  0.46400514],
        [-0.2258632 ,  0.3818766 ,  1.41984   ]],

       ...,

     

### 9. Create a tensor with shape [10] using your own choice of values, then find the index which has the maximum value

In [139]:
tensor = tf.constant([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
tensor

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int32)>

In [140]:
tf.argmax(tensor)

<tf.Tensor: shape=(), dtype=int64, numpy=9>

### 10. One-hot encode the tensor created in 9

In [142]:
tf.one_hot(tensor, depth=10, on_value='On', off_value='Off')

<tf.Tensor: shape=(10, 10), dtype=string, numpy=
array([[b'Off', b'On', b'Off', b'Off', b'Off', b'Off', b'Off', b'Off',
        b'Off', b'Off'],
       [b'Off', b'Off', b'On', b'Off', b'Off', b'Off', b'Off', b'Off',
        b'Off', b'Off'],
       [b'Off', b'Off', b'Off', b'On', b'Off', b'Off', b'Off', b'Off',
        b'Off', b'Off'],
       [b'Off', b'Off', b'Off', b'Off', b'On', b'Off', b'Off', b'Off',
        b'Off', b'Off'],
       [b'Off', b'Off', b'Off', b'Off', b'Off', b'On', b'Off', b'Off',
        b'Off', b'Off'],
       [b'Off', b'Off', b'Off', b'Off', b'Off', b'Off', b'On', b'Off',
        b'Off', b'Off'],
       [b'Off', b'Off', b'Off', b'Off', b'Off', b'Off', b'Off', b'On',
        b'Off', b'Off'],
       [b'Off', b'Off', b'Off', b'Off', b'Off', b'Off', b'Off', b'Off',
        b'On', b'Off'],
       [b'Off', b'Off', b'Off', b'Off', b'Off', b'Off', b'Off', b'Off',
        b'Off', b'On'],
       [b'Off', b'Off', b'Off', b'Off', b'Off', b'Off', b'Off', b'Off',
        b'Off',

In [133]:
tensor

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([65, 34, 23, 78, 65, 89, 47, 92, 98, 67], dtype=int32)>